= Crypto Lab
Abhishek Ojha <Abhishekojha38@gmail.com.com>
:toc:
:toclevels: 3
:icons: font
:sectnums:

== Introduction

Brief overview of what this guide covers:
* Key generation (RSA)
* Understand digital signature
* X.509 certificates (self-signed & CA-signed)

== Environment Setup

List prerequisites:
* OpenSSL ≥ 3.0
* bash
* asciidoctor for rendering

Example setup:
[source,bash]
----
sudo apt install openssl asciidoctor
----

== Encoding Formats

* PEM: ASCII Base64 encoding format. PEM certificates can have a file extension
of .pem, .crt, or .cer.The PEM format is the most common format that Certificate
Authorities issue certificates in. PEM certificates usually have extentions such
as .pem, .crt, .cer, and .key. They are Base64 encoded ASCII files and contain
"-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----" statements. Server
certificates, intermediate certificates, and private keys can all be put into
the PEM format. The PKCS12 format is preferred for exchanging certificates that
has private key(s).
----
-----BEGIN CERTIFICATE-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A...
-----END CERTIFICATE-----
----

* DER: The DER format is simply a binary form of a certificate instead of the
ASCII PEM format. It sometimes has a file extension of .der but it often has a
file extension of .cer so the only way to tell the difference between a DER .cer
file and a PEM .cer file is to open it in a text editor and look for the
BEGIN/END statements. All types of certificates and private keys can be encoded
in DER format.

* PKCS#5: Password-Based Encryption Standard. Protecting private keys with
passwords. Replaced by PKCS#12 (which is more general) and PKCS#8 for key
storage.

* PKCS#8: Standard syntax for storing private keys.Can be encrypted or
unencrypted. 
----
Unencrypted:
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----

Encrypted:
-----BEGIN ENCRYPTED PRIVATE KEY-----
...
-----END ENCRYPTED PRIVATE KEY-----
----

[NOTE]
--
PKCS #8 is a private key syntax for all algorithms and not just RSA. On the
other hand, PKCS1 is primarily for using the RSA algorithm.
--

* PKCS#10: Certificate Signing Request (CSR) format.
----
-----BEGIN CERTIFICATE REQUEST-----
...
-----END CERTIFICATE REQUEST-----
----

* PKCS#12: Container format for storing private key + certificate chain.
----
openssl pkcs12 -export -out bundle.p12 -inkey private.key -in cert.crt -certfile ca.crt
----

* PKCS#7: Format for signed or encrypted data (e.g., certificate chain or CMS).
Used for bundling multiple certificates (like intermediate + root).

[cols="1,2,2,2,1", options="header"]
|===
| Format / Standard | Purpose | Contains | Common Extension | Encoding

| PEM
| General container
| Certs / Keys
| .pem, .crt, .key
| Base64

| DER
| Binary form
| Certs / Keys
| .der, .cer
| Binary

| PKCS#5
| Password-based key derivation
| —
| —
| —

| PKCS#8
| Private key format
| Private key
| .p8, .key
| PEM/DER

| PKCS#10
| Certificate Signing Request
| CSR info + signature
| .csr
| PEM/DER

| PKCS#12
| Key + certificate chain container
| Private key + certs
| .p12, .pfx
| Binary

| PKCS#7 (CMS)
| Signed/encrypted message or cert chain. *Uses private key for signing but does not contain it.*
| Certs, signatures, encrypted data
| .p7b, .p7c
| Binary/PEM
|===


== Key Generation

* Generate Private key:
----
$ openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
$ cat private_key.pem 
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkUrjpLeCnuXXE
........
........
mMzOBHNsW8pIxInMBcUp3NM=
-----END PRIVATE KEY-----
----

* Extract Public Key:
----
$ openssl rsa -pubout -in private_key.pem -out public_key.pem
$ cat public_key.pem 
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApFK46S3gp7l1xJ7dzWnu
........
MF4fIkaSMeeXXxoDwamJvZrXqWR37QlzV+WRlCoHY5tWGTEhsKXmrvD7Yh0WNkP+
rQIDAQAB
-----END PUBLIC KEY-----
----

== Understand digital signature

A digital signature is a cryptographic method that ensures:

* `Authenticity`: Confirms the source of data.
* `Integrity`: Ensures the data hasn’t been modified.
* `Non-repudiation`: Prevents the signer from denying authorship.

`A Private Key` → used to sign data.
`A Public Key` → used to verify the signature.

=== Signing Process

The sender takes the original data.

* A hash function (e.g., SHA-256) is applied to produce a fixed-length digest.
* This hash is then encrypted with the sender’s private key → producing the digital signature.
* The signature is sent along with the data.

----
Data ──> Hash ──> Encrypt with Private Key ──> Digital Signature
----

==== Example

* Sample data
----
echo "Confidential data to sign" > data.txt
----

* Sign the data and generate digital signature.
----
openssl dgst -sha256 -sign private_key.pem -out signature.bin data.txt
----

* Verify signature
----
openssl dgst -sha256 -verify public_key.pem -signature signature.bin data.txt
----

== 5. Understand X509 Certificate

An X.509 certificate is a digital document that binds a public key to an
identity (like a user, computer, or server) and is used to verify authenticity
and enable secure communication. These certificates are a standard part of
Public Key Infrastructure (PKI), are issued by trusted Certificate Authorities
(CAs).

There are two common types:

* `Root CA Certificate` — A trusted Certificate Authority used to sign other
certificates.
* `Self-Signed Certificate` — A standalone certificate signed by its own private
key (used when no CA is involved).

=== Generate self-signed X509

* Generate Private key
----
openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
----

* Now there are two steps to genearte self-signed X509.
** Using -x509 option of openssl: You get a self-signed certificate in one step.
** Generate csr and then sign it with same private key which was used for csr.
  -x509 option also does same thing in the background.

==== Option 1: Using -x509 option

Generate self-signed x509 certificate.

* Creates a new certificate request internally.
* Immediately self-signs it using the same private key.
* Outputs the certificate (X.509 format), not the CSR.
----
$ openssl req -x509 -new -nodes -key private_key.pem -sha256 -days 3650 -out device.crt
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:CA
State or Province Name (full name) [Some-State]:Quebec
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:Company Solutions
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:device.company.solutions
Email Address []:
----

==== Option 2: Generate csr and then sign it with same private key.

* You explicitly create a Certificate Signing Request (CSR).
* Then you use openssl x509 to sign that CSR using the same private key.
* The result is a self-signed certificate, just like in `Option 1` — but via two
steps.

* Generate CSR, Hash of (Public Key + Identity Info) = Sign the Hash with
Private key which result in Digital signature. Append digital signature at the
end of CSR.
----
$ openssl req -new -key private_key.pem -out request.csr
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:CA
State or Province Name (full name) [Some-State]:Quebec
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:Company Solutions
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:device.company.solutions
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
----

* Generate X509 cert
----
openssl x509 -req -in request.csr -signkey private_key.pem -out cert.pem -days 365
Certificate request self-signature ok
subject=C=CA, ST=Quebec, O=Company Solutions, CN=device.company.solutions
----


=== Generate X509 Root CA

==== Create a Root CA Certificate

A Root CA is the top of the trust chain — it signs other certificates to make
them trusted.

* Generate Root CA Private Key
----
openssl genpkey -algorithm RSA -out root-pri.key -pkeyopt rsa_keygen_bits:4096
----

* Create Root CA Certificate
----
$ openssl req -x509 -new -nodes -key root-pri.key -sha256 -days 3650 -out rootCA.crt
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:CA
State or Province Name (full name) [Some-State]:Quebec
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:ROOTCA 
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:
----

[NOTE]
--
- -x509: Create a self-signed certificate (no CSR required).
- -days 3650: Valid for 10 years.
- -sha256: Use SHA-256 for signing.
--

* Verify Root CA Certificate. We can clearly see Data, Signature algo, Signature
(Data ──> Hash ──> Encrypt with Private Key ──> Digital Signature). Here
Encrypt with Private Key(Hash(data(Identitiy + PublicKey))) is
sha256WithRSAEncryption(data(Identitiy + PublicKey))
----
openssl x509 -in rootCA.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:43:12:87:22:c4:dd:82:2e:0b:9c:ee:fa:c5:0a:a5:73:eb:19:e5
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
        Validity
            Not Before: Oct 17 14:00:58 2025 GMT
            Not After : Oct 15 14:00:58 2035 GMT
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:b8:f3:eb:32:6d:95:5c:42:db:04:e5:12:c4:0d:
                    da:4c:8a:ee:44:45:9a:8c:73:b4:91:a6:80:9e:f4:
                    .........
                    16:d1:bb:e3:8a:d0:3c:12:62:a9:e4:85:ad:e2:62:
                    b0:82:63
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                E2:D7:F6:CF:B9:96:2C:A9:DF:75:04:20:4D:CD:B3:F9:AC:20:44:38
            X509v3 Authority Key Identifier: 
                E2:D7:F6:CF:B9:96:2C:A9:DF:75:04:20:4D:CD:B3:F9:AC:20:44:38
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        53:f5:56:db:7d:ca:1d:96:62:15:ed:68:2d:38:9e:74:4b:7c:
        .............
        7a:81:48:62:26:b5:74:49:b5:aa:17:e6:e1:a1:ff:c6:e2:df:
        3a:11:96:45:38:b5:8b:f9
----

=== Create a Device Certificate Signed by Root CA

Now we’ll create another certificate (for a device, web server, or user) that’s
signed by the Root CA.

* Generate Device Private Key.
----
openssl genpkey -algorithm RSA -out device.key -pkeyopt rsa_keygen_bits:2048
----

* Generate CSR (Certificate Signing Request)
Hash of (Public Key + Identity Info) = Sign the Hash with Private key which
result in Digital signature. Append digital signature at the end of CSR.
----
$ openssl req -new -key device.key -out device.csr
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
----

Enter details:
----
Country Name (2 letter code) [AU]:CA
State or Province Name (full name) [Some-State]:Quebec
Organization Name [Internet Widgits Pty Ltd]:Company Solutions
Common Name [localhost]:device.company.local
----

* Dump csr for understanding.
----
openssl req -in device.csr -text -noout
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c0:9e:7d:ed:6e:4d:22:da:b2:5a:a6:cd:06:9a:
                    78:4c:f9:4e:56:2e:d0:8c:68:42:aa:cd:31:cf:4b:
                    .............
                    9f:77:e1:29:10:c0:8a:50:c1:f7:86:6e:37:ed:71:
                    ab:3f
                Exponent: 65537 (0x10001)
        Attributes:
            (none)
            Requested Extensions:
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        7e:f0:a0:94:c1:38:98:82:59:d1:26:3f:a3:4c:90:a3:86:ba:
        .........
        0c:34:31:0c:78:75:17:9d:ab:24:00:f2:8d:92:32:bb:29:dc:
        46:95:0b:ec
----

* Create Configuration File for Extensions (Optional but Recommended)
----
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = device.company.local
----

* Sign the Device CSR with Root CA
----
$ openssl x509 -req -in device.csr -CA rootCA.crt -CAkey root-pri.key -CAcreateserial \
-out device.crt -days 730 -sha256 -extfile device_ext.cnf
Certificate request self-signature ok
subject=C = CA, ST = Quebec, O = Company Solutions, CN = device.company.local
----

* Verify the Signed Certificate
----
$ openssl x509 -in device.crt -text -noout
----

* Verify the Certificate Chain
----
$ openssl verify -CAfile rootCA.crt device.crt
device.crt: OK
----

== Refrences
* https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/
* https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs
* https://www.cem.me/20150104-cert-binaries-2.html
